package com.popov.fintrack.transaction.model;

public enum Category {
    //Expense
    FOOD, TRANSPORT, ENTERTAINMENT, UTILITIES, SHOPPING,
    HEALTH, HOME, BILLS_AND_FEES, CAR, TRAVEL, EDUCATION,
    CLOTHING, SPORT, GIFTS, CHARITY, RENT, SUBSCRIPTION,

    //Income
    SALARY, FREELANCE, SALES, BONUS, DIVIDENDS, INTEREST, REFUND,
    LOAN, INVESTMENT, PENSION, INSURANCE, CHILD_SUPPORT, ALIMONY,
    GOVERNMENT_BENEFITS, OTHER_INCOME, BANK_TRANSFER,

    OTHER
}
